Repository kazupon/args-tokens, pull requests merged in 2025-08, with the labels that each got.

#199 fix: correct malformed img tag attributes
  README.md
Labels: documentation

#205 feat(resolver): add conflicts option for mutually exclusive arguments
  README.md
  src/resolver.test.ts
  src/resolver.ts
Labels: feature

#224 perf: performance optimization for conflict checking
  src/resolver.ts
Labels: improvement, performance
